### ISSUE TITLE
RPM issue

### ISSUE THREAD

**Issue by fmanea** [hgomez/obuildfactory#55] opened 2017-07-27 14:17 UTC
Hello, it seems that the .rpm tool is adding this path on installation "/opt/obuildfactory/jdk-1.9.0-openjdk-x86_64/" and maybe it should have been something like this "/usr/lib/jvm/openjdk-9" - "/usr/lib64/jvm/openjdk-9", since you can't modify the path of the .rpm installation. I tried adding --prefix before installation, but it only adds an additionl path before "/opt/...". Another possibility would have been to only have the path without "/opt/obuildfactory/" and then when using ```rpm -i -prefix=/usr/lib/jvm``` it would install in the right place. Also, this kind of approach would add more weight on the end user.

**Comment by hgomez** [comment] 2017-07-28 05:57
/opt/obuildfactory location is by design, to install jvms outside stock jvms locations and avoid problems.

It's easy to update PATH and JAVA_HOME to enroll them

**Comment by fmanea** [comment] 2017-07-28 09:41
Also, there is a problem with the rpm files, meaning that they can't be installed on systems, due to this: https://github.com/jordansissel/fpm/issues/1386 . I can make a pull request regarding this.

**Comment by hgomez** [comment] 2017-07-28 12:18
I close this ticket and wait for your PR

**Closed by hgomez** 2017-07-28 12:18 UTC
